# Generated by Django 3.2 on 2022-11-01 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_news_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 11, 49, 12, 805441)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='slug',
            field=models.SlugField(default='Auto-Generate', editable=False),
        ),
    ]
