# Generated by Django 3.2 on 2022-11-01 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20221101_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_category',
            name='slug',
            field=models.SlugField(default='Auto-Generate', editable=False),
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 13, 5, 31, 415451)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 13, 5, 31, 414454)),
        ),
    ]
