# Generated by Django 3.2 on 2022-11-01 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20221101_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help_and_advice_table',
            options={'verbose_name_plural': 'Help and Advice'},
        ),
        migrations.AlterModelOptions(
            name='news_comments',
            options={'verbose_name_plural': 'News Comments'},
        ),
        migrations.AddField(
            model_name='help_and_advice_table',
            name='slug',
            field=models.SlugField(default='Auto-Generate', editable=False),
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 13, 29, 14, 630746)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 13, 29, 14, 629749)),
        ),
    ]
