# Generated by Django 3.2 on 2022-11-01 09:04

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20221101_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='organisation_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='organisation_img/')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('Long_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Get_in_touch_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 15, 4, 55, 697149)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 15, 4, 55, 696153)),
        ),
    ]
