# Generated by Django 3.2 on 2022-11-01 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20221101_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation_table',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='community.help_and_advice_table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 15, 8, 16, 784781)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 15, 8, 16, 782781)),
        ),
    ]
