# Generated by Django 3.2 on 2022-11-01 11:18

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20221101_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='Auto-Generate', editable=False)),
                ('From_Time', models.DateTimeField()),
                ('To_Time', models.DateTimeField()),
                ('Via', models.CharField(max_length=255)),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 17, 18, 55, 940565)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 17, 18, 55, 940565)),
        ),
    ]
