# Generated by Django 3.2 on 2022-11-01 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20221101_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_table',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 20, 26, 24, 611736)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 20, 26, 24, 611736)),
        ),
    ]
