# Generated by Django 3.2 on 2022-11-01 17:17

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20221101_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_vacancies_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='Auto-Generate', editable=False)),
                ('Short_Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='events/')),
            ],
            options={
                'verbose_name_plural': 'Report Table',
            },
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 23, 17, 28, 134437)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 23, 17, 28, 132380)),
        ),
    ]
