# Generated by Django 3.2 on 2022-11-02 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_auto_20221101_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEWSLETTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 17, 36, 5, 760749))),
            ],
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Last_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 2, 17, 36, 5, 760749)),
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 17, 36, 5, 760749)),
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 17, 36, 5, 760749)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 17, 36, 5, 760749)),
        ),
    ]
