# Generated by Django 3.2 on 2022-11-02 15:26

import datetime
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_auto_20221102_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url_link', embed_video.fields.EmbedVideoField()),
                ('short_description', models.TextField(blank=True, null=True)),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 21, 26, 9, 698750))),
            ],
            options={
                'verbose_name_plural': 'videos Table',
            },
        ),
        migrations.DeleteModel(
            name='post_youtube_video',
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Last_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 2, 21, 26, 9, 698750)),
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 21, 26, 9, 698750)),
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 21, 26, 9, 698750)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 21, 26, 9, 698750)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 21, 26, 9, 698750)),
        ),
    ]
