# Generated by Django 3.2 on 2022-11-02 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_auto_20221102_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location_ID', models.CharField(max_length=255)),
                ('District_or_Borough_Help', models.CharField(blank=True, max_length=255, null=True)),
                ('Contact_Name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('website_link', models.CharField(blank=True, max_length=255, null=True)),
                ('Charity_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Company_Registration_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Your_Name', models.CharField(max_length=255)),
                ('your_email', models.CharField(max_length=255)),
                ('Role_in_Organisation', models.CharField(max_length=255)),
                ('legal_advice', models.BooleanField(default=False)),
                ('education_matters', models.BooleanField(default=False)),
                ('health_wellbeing', models.BooleanField(default=False)),
                ('employment_jobs', models.BooleanField(default=False)),
                ('somali_mosques', models.BooleanField(default=False)),
                ('Music_Culture_Arts', models.BooleanField(default=False)),
                ('Sport_Recreation', models.BooleanField(default=False)),
                ('Housing', models.BooleanField(default=False)),
                ('Benefits_Debt', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Last_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 33, 11, 178966)),
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 33, 11, 178966)),
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 33, 11, 178966)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 33, 11, 178966)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 33, 11, 178966)),
        ),
        migrations.AlterField(
            model_name='videos_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 33, 11, 178966)),
        ),
    ]
