# Generated by Django 3.2 on 2022-11-02 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_auto_20221103_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Account_Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Last_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 48, 23, 359690)),
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 48, 23, 359690)),
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 48, 23, 359690)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 48, 23, 359690)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 48, 23, 359690)),
        ),
        migrations.AlterField(
            model_name='videos_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 48, 23, 359690)),
        ),
    ]
