# Generated by Django 3.2 on 2022-11-02 18:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0025_auto_20221103_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='User',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Last_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 58, 44, 762238)),
        ),
        migrations.AlterField(
            model_name='job_vacancies_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 58, 44, 762238)),
        ),
        migrations.AlterField(
            model_name='news_comments',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 58, 44, 762238)),
        ),
        migrations.AlterField(
            model_name='news_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 58, 44, 762238)),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 58, 44, 762238)),
        ),
        migrations.AlterField(
            model_name='videos_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 3, 0, 58, 44, 762238)),
        ),
    ]
